GET http://localhost:8080/api/auth/select
Accept: *

###

GET http://localhost:8080/api/auth/select/1
Accept: *

###

GET http://localhost:8080/api/auth/insert
Accept: *

###


POST http://localhost:8080/api/auth/insert
Content-Type: application/json

{
  "username": "testli",
  "plainPassword": "xxxxxxx",
  "lists": [
    {
      "title": "list-title",
      "items": [
        {
          "content": "item1"
        },
        {
          "content": "item2"
        },
        {
          "content": "item3"
        }
      ]
    }
  ]
}

###

POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "testli",
  "passwordSHA256": "xxxxxxx",
  "email": "xxxxx@yyy.zz"
}
