GET http://localhost:8080/api/auth/select
Accept: *

###

GET http://localhost:8080/api/auth/select/1
Accept: *

###

GET http://localhost:8080/api/auth/insert
Accept: *

###


POST http://localhost:8080/api/auth/insert
Content-Type: application/x-www-form-urlencoded

username=httpUser&password=httpPassword

